import type { Property, SiteContent } from "./types"

export const DEFAULT_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    type: "F3",
    title: "F3 Centre-Ville Oran",
    location: "Centre-Ville, Oran",
    price: "12 500 000 DA",
    surface: "78 m²",
    rooms: 3,
    condition: "Rénové",
    badge: "Nouveau",
    badgeColor: "bg-gold text-navy",
    features: ["Terrasse", "Double vitrage", "Lumineux"],
    description: "Bel appartement F3 entièrement rénové au cœur du centre-ville d'Oran. Lumineux, moderne et prêt à emménager.",
    image: "https://placehold.co/600x400?text=Appartement+F3+moderne+renove+centre+ville+Oran+salon+lumineux+parquet+bois+clair",
    status: "available",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prop-2",
    type: "F4",
    title: "F4 Standing Bir El Djir",
    location: "Bir El Djir, Oran",
    price: "18 000 000 DA",
    surface: "105 m²",
    rooms: 4,
    condition: "Neuf",
    badge: "Coup de cœur",
    badgeColor: "bg-navy text-white",
    features: ["Parking", "Gardien 24/7", "Résidence sécurisée"],
    description: "F4 neuf dans une résidence sécurisée à Bir El Djir. Finitions haut de gamme, parking et gardien.",
    image: "https://placehold.co/600x400?text=Appartement+F4+standing+neuf+Bir+El+Djir+Oran+cuisine+equipee+moderne",
    status: "available",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prop-3",
    type: "F2",
    title: "F2 Idéal Investissement",
    location: "Es Senia, Oran",
    price: "7 200 000 DA",
    surface: "52 m²",
    rooms: 2,
    condition: "Bon état",
    badge: "Investissement",
    badgeColor: "bg-secondary text-navy border border-gold/30",
    features: ["Proche université", "Forte demande locative", "Rentable"],
    description: "F2 idéalement situé à Es Senia, proche de l'université. Fort potentiel locatif avec une demande constante.",
    image: "https://placehold.co/600x400?text=Appartement+F2+investissement+Es+Senia+Oran+propre+lumineux+proche+transports",
    status: "available",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prop-4",
    type: "F3",
    title: "F3 Vue Mer Canastel",
    location: "Canastel, Oran",
    price: "16 500 000 DA",
    surface: "84 m²",
    rooms: 3,
    condition: "Excellent état",
    badge: "Exclusif",
    badgeColor: "bg-red-600/90 text-white",
    features: ["Vue mer", "Balcon", "Quartier prisé"],
    description: "Rare F3 avec vue mer panoramique à Canastel. Balcon spacieux, quartier résidentiel calme et prisé.",
    image: "https://placehold.co/600x400?text=Appartement+F3+vue+mer+panoramique+Canastel+Oran+balcon+terrasse+coucher+de+soleil",
    status: "available",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prop-5",
    type: "F4",
    title: "F4 Duplex Hai Maraval",
    location: "Hai Maraval, Oran",
    price: "22 000 000 DA",
    surface: "130 m²",
    rooms: 5,
    condition: "Neuf",
    badge: "Premium",
    badgeColor: "bg-gold text-navy",
    features: ["Duplex", "Grande terrasse", "Finitions haut de gamme"],
    description: "Exceptionnel duplex F4 dans le quartier prisé de Hai Maraval. Double hauteur, terrasse panoramique et finitions premium.",
    image: "https://placehold.co/600x400?text=Duplex+F4+premium+Hai+Maraval+Oran+double+hauteur+escalier+design+terrasse+panoramique",
    status: "available",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prop-6",
    type: "F3",
    title: "F3 Hassi Ben Okba",
    location: "Hassi Ben Okba, Oran",
    price: "9 800 000 DA",
    surface: "72 m²",
    rooms: 3,
    condition: "À rénover",
    badge: "Bonne affaire",
    badgeColor: "bg-green-700 text-white",
    features: ["Fort potentiel", "Prix négociable", "Calme"],
    description: "F3 à rénover avec un fort potentiel à Hassi Ben Okba. Prix négociable, environnement calme et lumineux.",
    image: "https://placehold.co/600x400?text=Appartement+F3+a+renover+Hassi+Ben+Okba+Oran+bon+potentiel+lumiere+naturelle",
    status: "available",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const DEFAULT_CONTENT: SiteContent = {
  hero: {
    headline: "Trouvez le bien qui vous correspond, sans perdre de temps.",
    subheadline:
      "Je suis Chabane Chawki, agent immobilier à Oran. Je ne travaille pas comme une agence traditionnelle — j'utilise le marketing et la vidéo pour attirer des acheteurs sérieux et vous faire gagner un temps précieux.",
    badge: "Oran, Algérie — Immobilier Premium",
    backgroundImage: "https://placehold.co/1920x1080?text=Vue+panoramique+de+la+ville+d+Oran+Algerie+avec+architecture+moderne+et+ciel+bleu+mediteraneen",
    stat1Value: "100+",
    stat1Label: "Biens vendus",
    stat2Value: "48h",
    stat2Label: "Délai moyen de contact",
    stat3Value: "Oran",
    stat3Label: "Expert local",
    ctaPrimaryText: "Me contacter sur WhatsApp",
    ctaSecondaryText: "Voir les biens disponibles",
  },
  about: {
    headline: "Je ne suis pas un agent immobilier classique.",
    subheadline: "Je suis un vendeur de biens.",
    paragraph1:
      "Je m'appelle Chabane Chawki, fondateur de Chabano Properties. J'ai choisi de construire ma marque différemment : là où les agences traditionnelles font de la pub générique, moi je crée du contenu vidéo qui met en valeur chaque bien et attire des acheteurs qui savent ce qu'ils veulent.",
    paragraph2:
      "Mon objectif est simple : vous faire gagner du temps, vous éviter les visites inutiles, et vous connecter avec les bonnes personnes — que vous vendiez ou que vous achetiez. Oran est ma ville, je la connais quartier par quartier.",
    yearsExperience: "5+",
    experienceLabel: "ans dans l'immobilier à Oran",
    profileImage: "https://placehold.co/600x750?text=Portrait+professionnel+de+Chabane+Chawki+agent+immobilier+moderne+a+Oran+Algerie+costume+elegant+confiant",
  },
  services: {
    sectionLabel: "Ce que je fais",
    sectionTitle: "Un accompagnement sur mesure,",
    sectionSubtitle: "Acheteur, vendeur, investisseur — chaque profil mérite une approche différente. Voici comment je travaille.",
    service1: {
      tag: "Achat",
      title: "Vous cherchez à acheter ?",
      desc: "F2, F3, F4 — peu importe votre budget ou votre quartier préféré, je connais les bons biens avant même qu'ils soient publiés. Fini les annonces floues et les visites pour rien.",
      benefit1: "Sélection personnalisée selon vos critères",
      benefit2: "Visites vidéo avant déplacement",
      benefit3: "Accompagnement jusqu'à la signature",
      cta: "Je cherche un appartement",
    },
    service2: {
      tag: "Vente",
      title: "Vous vendez votre bien ?",
      desc: "Je ne mets pas juste une annonce et j'attends. Je crée une vidéo professionnelle, je la distribue à mes acheteurs, et j'attire des clients sérieux en quelques jours.",
      benefit1: "Vidéo professionnelle de votre bien",
      benefit2: "Diffusion sur mes réseaux qualifiés",
      benefit3: "Acheteurs sérieux uniquement",
      cta: "Vendre mon bien",
    },
    service3: {
      tag: "Investissement",
      title: "Vous investissez ?",
      desc: "Oran est en pleine mutation. Je vous guide sur les zones à fort potentiel, les biens sous-évalués, et les opportunités que les portails ne montrent pas.",
      benefit1: "Analyse des quartiers porteurs",
      benefit2: "Opportunités off-market",
      benefit3: "Conseil rentabilité locative",
      cta: "Découvrir les opportunités",
    },
  },
  video: {
    sectionLabel: "Mon avantage",
    headline: "Vos biens, présentés comme des propriétés de prestige",
    paragraph1:
      "La plupart des agents postent quelques photos floues et attendent. Moi, je fais des vidéos qui montrent chaque bien sous son meilleur angle — lumière naturelle, angles stratégiques, narration qui donne envie.",
    paragraph2:
      "Résultat : les acheteurs arrivent déjà convaincus. Les visites sont plus courtes, les décisions plus rapides, et les ventes se concluent sans négociations interminables.",
    videoThumbnail: "https://placehold.co/700x400?text=Video+professionnelle+appartement+F3+Oran+tournage+drone+interieur+lumineux+qualite+cinema",
    stat1Value: "3x",
    stat1Label: "plus de visites sérieuses",
    ctaText: "Demander une visite vidéo",
  },
  testimonials: {
    sectionLabel: "Ils témoignent",
    headline: "Des résultats concrets,",
    subtitle: "Voici ce que disent les clients qui ont fait confiance à Chabano Properties.",
    testimonial1: {
      name: "Karim B.",
      role: "Acheteur — F3 Centre-Ville",
      text: "J'ai cherché pendant 6 mois sur les portails sans rien trouver de sérieux. Chabane m'a trouvé mon appartement en 3 semaines, avec une vidéo qui m'a convaincu avant même la visite. Efficace et professionnel.",
      stars: 5,
      avatar: "K",
    },
    testimonial2: {
      name: "Samira O.",
      role: "Vendeuse — Bir El Djir",
      text: "Mon appartement était sur le marché depuis 4 mois. Après la vidéo de Chabane, j'ai reçu 3 offres sérieuses en une semaine. Je n'aurais pas cru que la présentation faisait autant la différence.",
      stars: 5,
      avatar: "S",
    },
    testimonial3: {
      name: "Mourad L.",
      role: "Investisseur — Portefeuille locatif",
      text: "Je travaille avec Chabane depuis 2 ans pour mes investissements à Oran. Il connaît le marché mieux que personne et m'a orienté vers des biens avec un excellent rendement locatif. Partenaire de confiance.",
      stars: 5,
      avatar: "M",
    },
    result1: { value: "48h", label: "Délai moyen de premier contact" },
    result2: { value: "94%", label: "Taux de satisfaction client" },
    result3: { value: "3×", label: "Plus vite qu'une agence classique" },
    result4: { value: "100+", label: "Biens traités à Oran" },
  },
  finalCta: {
    label: "Prêt à agir ?",
    headline: "Votre bien à Oran",
    headlineGold: "vous attend déjà.",
    subtitle: "Chaque jour passé à hésiter, c'est une opportunité qui disparaît. Parlons maintenant — je vous trouve ce que vous cherchez, rapidement et sérieusement.",
    ctaPrimaryText: "Démarrer maintenant sur WhatsApp",
    ctaSecondaryText: "Appeler Chabane",
    availabilityText: "Réponse garantie en moins de 2 heures — Disponible 7j/7 de 9h à 21h",
  },
  footer: {
    brandName: "Chabano Properties",
    brandTagline: "Oran, Algérie",
    brandSubtitle: "Par Chabane Chawki — Agent Immobilier & Créateur de contenu",
    instagramUrl: "#",
    youtubeUrl: "#",
  },
  contact: {
    whatsappNumber: "213541029014",
    availabilityText: "Disponible du samedi au jeudi, de 9h à 21h. Je réponds généralement en moins de 2 heures.",
  },
}
